# Generated by Django 4.2.4 on 2023-08-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('temp', models.FloatField(null=True)),
                ('clarity', models.FloatField(null=True)),
                ('conductivity', models.FloatField(null=True)),
                ('pH', models.FloatField(null=True)),
                ('alkalinity', models.FloatField(null=True)),
                ('chlorine', models.FloatField(null=True)),
                ('oxygen_dissolved', models.FloatField(null=True)),
                ('hardness', models.FloatField(null=True)),
            ],
        ),
    ]
