# Generated by Django 4.2.4 on 2023-08-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterquality',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
