# Generated by Django 4.2.4 on 2023-08-08 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_api', '0002_alter_waterquality_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterquality',
            old_name='temp',
            new_name='temperature',
        ),
    ]
